- name: Add apt-key for docker repository
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
- name: Add docker's apt repository
  apt_repository:
    repo: deb https://get.docker.com/ubuntu docker main
    update_cache: yes
    state: present
- name: Install the lxc-docker package
  apt:
    name: lxc-docker
    state: present
